[package]
name = "discord-bot"
version = "0.1.0"
authors = ["nils <nils@nilsand.re>"]
edition = "2018"

[dependencies]
serenity = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
