[package]
name = "discord-bot"
version = "0.1.0"
authors = ["nils <nils@nilsand.re>"]
edition = "2018"

[dependencies]
serenity = "0.7"
staticvec = "0.7"

compile_time_serde = { path = "compile_time_serde" }

[profile.release]
lto = true
