steps:
- name: gcr.io/cloud-builders/docker
  args: [ pull, gcr.io/$PROJECT_ID/github.com/bafta-ygd-community/discord-bot:latest ]
- name: gcr.io/cloud-builders/docker
  args: [ build, -t, gcr.io/$PROJECT_ID/github.com/bafta-ygd-community/discord-bot:latest, --cache-from, gcr.io/$PROJECT_ID/github.com/bafta-ygd-community/discord-bot:latest, . ]
- name: gcr.io/cloud-builders/docker
  args: [ push, gcr.io/$PROJECT_ID/github.com/bafta-ygd-community/discord-bot:latest ]
- name: gcr.io/cloud-builders/gcloud
  args: [ compute, instances, update-container, discord-bot, --container-image, gcr.io/$PROJECT_ID/github.com/bafta-ygd-community/discord-bot:latest, --zone, europe-west2-b ]

timeout: 1500s
