steps:
- name: gcr.io/cloud-builders/docker
  args: [ build, -t, gcr.io/$PROJECT_ID/$REPO_NAME, --cache-from, gcr.io/$PROJECT_ID/$REPO_NAME, . ]

images: [ 'gcr.io/$PROJECT_ID/$REPO_NAME' ]

timeout: 1500s
